name 'light-locker'
maintainer 'Embedded Now, Inc'
maintainer_email 'hello@embeddednow.com'
license 'all_rights'
description 'Removes light-locker'
long_description 'Removes light-locker'
version '0.1.0'
