name 'light-locker'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures light-locker'
long_description 'Installs/Configures light-locker'
version '0.1.0'
